include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  # simulator_prod:
  #   build:
  #     context: .
  #     target: final
  #     dockerfile: Dockerfile.prod
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #     - kafka

  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
      - kafka
    volumes:
      - .:/app
