services:
  app-backend:
    build:
      context: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  db:
    build:
      context: ./.docker/mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
