include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  app-backend:
    build:
      context: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

